namespace Rasterizr.Diagnostics
{
	public enum OperationType
	{
		BlendStateCreate,
		BufferCreate,
		DepthStencilStateCreate,
		DepthStencilViewCreate,
		DeviceContextClearDepthStencilView,
		DeviceContextClearRenderTargetView,
		DeviceContextDraw,
		DeviceContextDrawIndexed,
		DeviceContextDrawInstanced,
		DeviceCreate,
		InputAssemblerStageSetIndexBuffer,
		InputAssemblerStageSetInputLayout,
		InputAssemblerStageSetPrimitiveTopology,
		InputAssemblerStageSetVertexBuffers,
		InputLayoutCreate,
		PixelShaderCreate,
		PixelShaderStageSetShader,
		RasterizerStateCreate,
		RenderTargetViewCreate,
		SwapChainCreate,
		SwapChainPresent,
		Texture2DCreate,
		VertexShaderCreate,
		VertexShaderStageSetShader,
	}
}