namespace Rasterizr.Diagnostics
{
	public enum OperationType
	{
		CreateBlendState,
		CreateBuffer,
		CreateDepthStencilState,
		CreateDepthStencilView,
		DeviceContextClearDepthStencilView,
		DeviceContextClearRenderTargetView,
		DeviceContextDraw,
		DeviceContextDrawIndexed,
		DeviceContextDrawInstanced,
		DeviceCreate,
		InputAssemblerStageSetIndexBuffer,
		InputAssemblerStageSetInputLayout,
		InputAssemblerStageSetPrimitiveTopology,
		InputAssemblerStageSetVertexBuffers,
		InputLayoutCreate,
		PixelShaderCreate,
		PixelShaderStageSetShader,
		RasterizerStateCreate,
		CreateRenderTargetView,
		SwapChainCreate,
		SwapChainPresent,
		CreateTexture1D,
		CreateTexture2D,
		CreateTexture3D,
		VertexShaderCreate,
		VertexShaderStageSetShader,
	}
}