using System.Collections.Generic;
using System.Linq;
using System.Text;
using SlimShader.IO;
using SlimShader.InputOutputSignature;
using SlimShader.ResourceDefinition;
using SlimShader.Shader;
using SlimShader.Util;

namespace SlimShader
{
	public class DxbcContainer
	{
		public DxbcContainerHeader Header { get; private set; }
		public List<DxbcChunk> Chunks { get; private set; }

		public ResourceDefinitionChunk ResourceDefinition
		{
			get { return Chunks.OfType<ResourceDefinitionChunk>().FirstOrDefault(); }
		}

		public InputSignatureChunk InputSignature
		{
			get { return Chunks.OfType<InputSignatureChunk>().FirstOrDefault(); }
		}

		public OutputSignatureChunk OutputSignature
		{
			get { return Chunks.OfType<OutputSignatureChunk>().FirstOrDefault(); }
		}

		public ShaderProgramChunk Shader
		{
			get { return Chunks.OfType<ShaderProgramChunk>().FirstOrDefault(); }
		}

		public StatisticsChunk Statistics
		{
			get { return Chunks.OfType<StatisticsChunk>().FirstOrDefault(); }
		}

		public DxbcContainer()
		{
			Chunks = new List<DxbcChunk>();
		}

		public static DxbcContainer Parse(BytecodeReader reader)
		{
			var container = new DxbcContainer();

			uint fourCc = reader.ReadUInt32();
			if (fourCc != "DXBC".ToFourCc())
				throw new ParseException("Invalid FourCC");

			var uniqueKey = new uint[4];
			uniqueKey[0] = reader.ReadUInt32();
			uniqueKey[1] = reader.ReadUInt32();
			uniqueKey[2] = reader.ReadUInt32();
			uniqueKey[3] = reader.ReadUInt32();

			container.Header = new DxbcContainerHeader
			{
				FourCc = fourCc,
				UniqueKey = uniqueKey,
				One = reader.ReadUInt32(),
				TotalSize = reader.ReadUInt32(),
				ChunkCount = reader.ReadUInt32()
			};

			for (uint i = 0; i < container.Header.ChunkCount; i++)
			{
				uint chunkOffset = reader.ReadUInt32();
				var chunkReader = reader.CopyAtOffset((int) chunkOffset);
				container.Chunks.Add(DxbcChunk.ParseChunk(chunkReader, container));
			}

			return container;
		}

		public override string ToString()
		{
			var sb = new StringBuilder();
			sb.AppendLine("// ");
			sb.AppendLine("// Generated by Shaderflect " + GetType().Assembly.GetName().Version);
			sb.AppendLine("// ");
			sb.AppendLine("// ");
			sb.AppendLine("// ");

			sb.AppendLine("//");
			sb.AppendLine("//");

			if (ResourceDefinition != null)
				sb.Append(ResourceDefinition);

			sb.AppendLine(@"//");
			sb.AppendLine(@"//");
			sb.AppendLine(@"//");

			if (InputSignature != null)
				sb.Append(InputSignature);

			sb.AppendLine(@"//");
			sb.AppendLine(@"//");

			if (OutputSignature != null)
				sb.Append(OutputSignature);

			sb.AppendLine(@"//");

			if (Shader != null)
				sb.Append(Shader);

			return sb.ToString();
		}
	}
}