namespace SlimShader.ObjectModel
{
	public enum InterpolationMode
	{
		INTERPOLATION_UNDEFINED = 0,
		INTERPOLATION_CONSTANT = 1,
		INTERPOLATION_LINEAR = 2,
		INTERPOLATION_LINEAR_CENTROID = 3,
		INTERPOLATION_LINEAR_NOPERSPECTIVE = 4,
		INTERPOLATION_LINEAR_NOPERSPECTIVE_CENTROID = 5,
		INTERPOLATION_LINEAR_SAMPLE = 6,
		INTERPOLATION_LINEAR_NOPERSPECTIVE_SAMPLE = 7
	}
}